version: 2
jobs:
  build:
    working_directory: ~/swift-ecs-ecr
    docker:
      - image: addli/swift:latest # Installed pip,aws-cli,jq and docker-client to swift:3.1.
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: show environments
          command: |
            cat /etc/issue
      - run:
          name: Run build tests
          command: |
            swift package clean
            swift build
      - run:
          name: Build image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/swift-sample-webapp:$CIRCLE_SHA1 .
      - run:
          name: Test container
          command: |
            docker run -d -p 8080:8080 --name swift-sample-webapp-container $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/swift-sample-webapp:$CIRCLE_SHA1;sleep 3
            docker run --network container:swift-sample-webapp-container appropriate/curl --retry 10 --retry-delay 5 http://localhost:8080/plaintext
      - run:
          name: Deploy image
          command: |
            sleep 3;./deploy.sh
