version: 2
jobs:
  build:
    # Should be use releative path when build on local machine.
    working_directory: ~/swift-ecs-ecr
    docker:
      - image: addli/swift:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: show environments
          command: |
            cat /etc/issue
      - run:
          name: Deploy image
          command: |
            ./deploy.sh
      - run:
          name: Run build tests
          command: |
            swift package clean
            swift build
      - run:
          name: Build image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/swift-sample-webapp:$CIRCLE_SHA1 .
      - run:
          name: Test container
          command: |
            docker run -d -p 8080:8080 --name swift-sample-webapp-container $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/swift-sample-webapp:$CIRCLE_SHA1;sleep 3
            docker exec swift-sample-webapp-container curl --retry 10 --retry-delay 5 localhost:8080/plaintext | grep 'Hello, world!'
      - run:
          name: Deploy image
          command: |
            ./deploy.sh
